language: objective-c
before_install:
  - gem install cocoapods --no-ri --no-rdoc
  - gem install xcpretty  --no-ri --no-rdoc

install:
  - cd TestProject
  - pod install
  - cd ..
script:
  - make ci

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c91f8833599a7a3e94eb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

