language: objective-c
before_install:
  - gem install cocoapods --no-ri --no-rdoc
  - gem install xcpretty  --no-ri --no-rdoc
install:
  - pod install
script:
  - make ci

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1a121b777d50c968fde
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always

