language: objective-c
before_install:
  - gem install cocoapods --no-ri --no-rdoc
  - gem install xcpretty  --no-ri --no-rdoc
install:
  - pod install
script: 
  - make ci | xcpretty -c; exit ${PIPESTATUS[0]}

notifications:
  webhooks:
    - https://alcatraz.slack.com/services/hooks/travis?token=S0o4aeCC7ZGBNiaMyGMv5Fed

